### ISSUE TITLE
Does this watch work with wearOS 4 pixel watch 1?

### ISSUE THREAD

**Issue by rami-maalouf** [blunden/DoNotDisturbSync#10]

**Comment by blunden** [comment]
I thought the Pixel Watch has that functionality built-in already?

Regardless, the answer is very likely yes since it's entirely generic. 🙂 As long as one of the devices run some form of Wear OS (or Android Wear) and the phone and watch both have Google Play Services installed (for the Wear OS watch communication API), it should work.
